resources:
  - deployment.yaml
patches:
  - patch: |-
      -  op: replace
         path: /spec/replicas
         value: 2
    target:
      group: apps
      version: v1
      kind: Deployment
  - patch: |-
      - op: replace
        path: /metadata/annotations/deployment.kubernetes.io~1revision
        value: 2
    target:
      group: apps
      version: v1
      kind: Deployment