apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: demo-mongo
    application: demo-mongo
    createdBy: ZCVV
  name: demo-mongo
  namespace: tst-namespace-default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-mongo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demo-mongo
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: DEV
        - name: SPRING_CONFIG_LOCATION
          value: file:/usr/app/config/
        - name: SPRING_APPLICATION_NAME
          value: demo-mongo
        - name: MY_CPU
          valueFrom:
            configMapKeyRef:
              key: CPU_REQUEST
              name: parameter-cm
        - name: MY_REPLICAS
          valueFrom:
            configMapKeyRef:
              key: REPLICAS_NUM
              name: parameter-cm
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              key: ENVIRONMENT_DEFAULT
              name: parameter-cm
        image: zelmarcvv/demo-mongo
        imagePullPolicy: Always
        name: demo-mongo
        resources:
          limits:
            cpu: 500m
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/app/config/
          name: demo-mongo-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: demo-mongo-volume
        projected:
          defaultMode: 420
          sources:
          - configMap:
              name: demo-mongo-cm
          - configMap:
              name: parameter-cm