apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: {{.Values.appName}}
    application: {{.Values.appName}}
    createdBy: ZCVV
  name: {{.Values.appName}}
  namespace: tst-namespace-default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{.Values.appName}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{.Values.appName}}
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: {{.Values.env}}
        - name: SPRING_PROFILES_ACTIVE
          value: {{.Values.springProfileActive}}
        - name: SPRING_CONFIG_LOCATION
          value: file:/usr/app/config/
        - name: SPRING_APPLICATION_NAME
          value: {{.Values.appName}}
        image: {{.Values.image}}
        imagePullPolicy: Always
        name: {{.Values.appName}}
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/app/config/
          name: {{.Values.appName}}-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: {{.Values.appName}}-volume
        projected:
          defaultMode: 420
          sources:
          - configMap:
              name: {{.Values.appName}}-cm
